import os
import re

filepath = 'lib/presentation/screens/checkout_screen.dart'
with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

# Using regex to replace the order creation block precisely.
pattern = r"final order = PrescriptionOrder\(\s*id: '', // Will be generated by Repository/Firestore\s*userId: authState\.user\.id,\s*patientName: authState\.user\.displayName \?\? 'Unknown Patient',\s*patientLocationName: fullAddress,\s*patientCoordinates: \[0\.0, 0\.0\], // Placeholder, real app would get lat/lng\s*date: DateTime\.now\(\),\s*deliveryFee: 1500\.0, // Standard fee\s*\);"

replacement = '''final order = PrescriptionOrder(
        id: '', // Will be generated by Repository/Firestore
        userId: authState.user.id,
        patientName: authState.user.displayName ?? 'Unknown Patient',
        patientPhone: _phoneController.text.isNotEmpty ? _phoneController.text : null,
        patientLocationName: fullAddress,
        patientCoordinates: [0.0, 0.0], // Placeholder, real app would get lat/lng
        date: DateTime.now(),
        items: items,
        pharmacyPrice: totalAmount,
        deliveryFee: 1500.0, // Standard fee
      );'''

new_content = re.sub(pattern, replacement, content)

if new_content != content:
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print("Fixed checkout_screen.dart via regex")
else:
    print("Regex failed to match.")
