import os

filepath = 'lib/presentation/screens/checkout_screen.dart'
old_code = '''      // Create Order Object
      final order = PrescriptionOrder(
        id: '', // Will be generated by Repository/Firestore
        userId: authState.user.id,
        patientName: authState.user.displayName ?? 'Unknown Patient',
        patientLocationName: fullAddress,
        patientCoordinates: [0.0, 0.0], // Placeholder, real app would get lat/lng
        date: DateTime.now(),
        deliveryFee: 1500.0, // Standard fee
      );'''

new_code = '''      // Create Order Object
      final order = PrescriptionOrder(
        id: '', // Will be generated by Repository/Firestore
        userId: authState.user.id,
        patientName: authState.user.displayName ?? 'Unknown Patient',
        patientPhone: _phoneController.text, // Added phone
        patientLocationName: fullAddress,
        patientCoordinates: [0.0, 0.0], // Placeholder, real app would get lat/lng
        date: DateTime.now(),
        items: items, // Added cart items
        pharmacyPrice: totalAmount, // Added cart total amount
        deliveryFee: 1500.0, // Standard fee
      );'''

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

if old_code in content:
    content = content.replace(old_code, new_code)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print("Fixed checkout_screen.dart")
else:
    print("Could not find the block to replace!")
