// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADZC0l9p8Mn6IsFAz-4DBGR7opME-BEXw',
    appId: '1:824975096050:web:11a0ded6a373be0063786b',
    messagingSenderId: '824975096050',
    projectId: 'farumasi-app',
    authDomain: 'farumasi-app.firebaseapp.com',
    storageBucket: 'farumasi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40eQjB9kOTLkSfLi7OtC7cKCBcl4olQo',
    appId: '1:824975096050:android:1517948e336b9e1363786b',
    messagingSenderId: '824975096050',
    projectId: 'farumasi-app',
    storageBucket: 'farumasi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNLAEBk1vA5FTUVRqfK75vkte_1r2eac',
    appId: '1:824975096050:ios:ce662984110335ee63786b',
    messagingSenderId: '824975096050',
    projectId: 'farumasi-app',
    storageBucket: 'farumasi-app.firebasestorage.app',
    iosBundleId: 'com.example.farumasiPatientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxNLAEBk1vA5FTUVRqfK75vkte_1r2eac',
    appId: '1:824975096050:ios:ce662984110335ee63786b',
    messagingSenderId: '824975096050',
    projectId: 'farumasi-app',
    storageBucket: 'farumasi-app.firebasestorage.app',
    iosBundleId: 'com.example.farumasiPatientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADZC0l9p8Mn6IsFAz-4DBGR7opME-BEXw',
    appId: '1:824975096050:web:d7246a6f8656a7b663786b',
    messagingSenderId: '824975096050',
    projectId: 'farumasi-app',
    authDomain: 'farumasi-app.firebaseapp.com',
    storageBucket: 'farumasi-app.firebasestorage.app',
  );
}
